version: "3.9"

services:
  backend:
    # build: ./backend
    image: ghcr.io/Debang5hu/backend:latest
    container_name: VulnTour_APIServer
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_FILE=/data/database.sqlite3
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1,http://localhost
    networks:
      - lab

  frontend:
    # build: ./frontend
    image: ghcr.io/Debang5hu/frontend:latest
    container_name: VulnTour_Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lab

networks:
  lab:
    driver: bridge
